name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Pipfile'

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: python -m pip install build

      - name: Install poetry
        run: make install-poetry

      - name: Install dependencies
        run: make install-env

      - name: Build and Deploy docs
        run: make deploy-docs