name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
      - run: python -m pip install build
      - name: Install poetry
        run: make install-poetry
      - name: Install dependencies
        run: make install-env
      - name: Build llm-wrapper package
        run: make build
      - name: Publish llm-wrapper package
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          args: --verbose
          user: "" # TODO: open-source
          password: "" # TODO: open-source
          repository_url: "" # TODO: open-source
