name: Release
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
      - run: python -m pip install build
      - name: Install poetry
        run: make install-poetry
      - name: Install dependencies
        run: make install-env
      - name: Build allms package
        run: make build
      - name: Publish allms package to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          make publish
        
